<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:ns2="http://www.tibco.com/pe/DeployedVarsType" xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:ns1="http://www.tibco.com/pe/EngineTypes" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.tibco.com/cim/services/mastercatalogrecord/wsdl/2.0" xmlns:ns3="http://three.co.uk/xsd/resource/common/commondefinitions/msf/exceptioninfo/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pfx5="http://three.co.uk/xsd/resource/common/commondefinitions/msf/exception/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx4="http://www.tibco.com/pe/GenerateErrorActivity/InputSchema" xmlns:pfx3="http://www.tibco.com/cim/services/mastercatalogrecordworkitem/wsdl/2.0" xmlns:pfx2="http://www.tibco.com/schemas/OrderFallout/Shared Resource/Schema/common/exceptionClassification/exceptionClassification.xsd" xmlns:pfx="http://www.tibco.com/AFF/V4.0.0/applications/orchestrator/message">
    <xsd:import namespace="http://www.tibco.com/schemas/OrderFallout/Shared Resource/Schema/common/exceptionClassification/exceptionClassification.xsd" schemaLocation="/SharedResources/SchemaDefinitions/Interface/ManagedEntityABE/ManagementEntityABE/exceptionClassification/exceptionClassification.xsd"/>
    <xsd:import namespace="http://www.tibco.com/AFF/V4.0.0/applications/orchestrator/message" schemaLocation="/SharedResources/SchemaDefinitions/Resource/FOS/orchestrator/sharedResources/schemas/classes/message.xsd"/>
    <xsd:import namespace="http://three.co.uk/xsd/resource/common/commondefinitions/msf/exception/v1" schemaLocation="/SharedResources/SchemaDefinitions/Resource/Common/CommonDefinitions/MSF/Exception_v1.xsd"/>
    <wsdl:import namespace="http://www.tibco.com/cim/services/mastercatalogrecordworkitem/wsdl/2.0" location="/SharedResources/WebServiceDefinitions/External/CIM/Cim_Services.wsdl"/>
    <pd:name>IntegrationServices/OrderFallout/FOSExceptionHandler_v1/Sub/Classify Exception.process</pd:name>
    <pd:startName>Start</pd:startName>
    <pd:startType>
        <xsd:element name="root">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element ref="pfx:message" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
    </pd:startType>
    <pd:startX>265</pd:startX>
    <pd:startY>80</pd:startY>
    <pd:returnBindings>
        <xsl:variable name="var_ExceptionId" select="$Start/root/pfx:message/pfx:code"/>
        <root>
            <xsl:choose>
                <xsl:when test="exists($GetVariable/pfx2:exceptionClassifications/pfx2:exceptionClassification[pfx2:exceptionCode=$var_ExceptionId]/pfx2:classification)">
                    <xsl:copy-of select="$GetVariable/pfx2:exceptionClassifications/pfx2:exceptionClassification[pfx2:exceptionCode=$var_ExceptionId]"/>
                </xsl:when>
                <xsl:otherwise>
                    <pfx2:exceptionClassification>
                        <pfx2:exceptionCode>
                            <xsl:value-of select="$_globalVariables/ns2:GlobalVariables/ExceptionCodes/MSF/Unclassified-Errors/Internal-Error/Code"/>
                        </pfx2:exceptionCode>
                        <pfx2:classification>
                            <pfx2:exceptionType>
                                <xsl:value-of select="&quot;Undefined&quot;"/>
                            </pfx2:exceptionType>
                            <pfx2:exceptionMessage>
                                <xsl:value-of select="&quot;Undefined&quot;"/>
                            </pfx2:exceptionMessage>
                        </pfx2:classification>
                    </pfx2:exceptionClassification>
                </xsl:otherwise>
            </xsl:choose>
        </root>
    </pd:returnBindings>
    <pd:endName>End</pd:endName>
    <pd:endType>
        <xsd:element name="root">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element ref="pfx2:exceptionClassification"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
    </pd:endType>
    <pd:endX>531</pd:endX>
    <pd:endY>81</pd:endY>
    <pd:errorSchemas>
        <Schema0 ref="pfx5:Exception"/>
    </pd:errorSchemas>
    <pd:processVariables/>
    <pd:targetNamespace>http://xmlns.example.com/1416832133808</pd:targetNamespace>
    <pd:activity name="Generate Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>545</pd:x>
        <pd:y>191</pd:y>
        <config>
            <faultName>Schema0</faultName>
        </config>
        <pd:inputBindings>
            <pfx4:ActivityInput>
                <data>
                    <xsl:copy-of select="$CreateBusinessException/root/pfx5:Exception"/>
                </data>
            </pfx4:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="GetVariable">
        <pd:type>com.tibco.pe.core.GetSharedVariableActivity</pd:type>
        <pd:resourceType>ae.activities.getSharedVariable</pd:resourceType>
        <pd:x>393</pd:x>
        <pd:y>81</pd:y>
        <config>
            <variableConfig>/SharedResources/SharedVariables/Variable/Error Code List.sharedvariable</variableConfig>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="CreateBusinessException">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>397</pd:x>
        <pd:y>192</pd:y>
        <config>
            <processName>/UtilityProcesses/Exceptions/CreateBusinessException.process</processName>
        </config>
        <pd:inputBindings>
            <root>
                <ExceptionCode>
                    <xsl:value-of select="$_globalVariables/ns2:GlobalVariables/ExceptionCodes/MSF/Activity-Errors/Unable-To-Get-Data-Error/Code"/>
                </ExceptionCode>
                <Severity>
                    <xsl:value-of select="$_globalVariables/ns2:GlobalVariables/MSF/Exceptions/Severity/Error"/>
                </Severity>
                <Description>
                    <xsl:value-of select="$_globalVariables/ns2:GlobalVariables/ExceptionCodes/MSF/Activity-Errors/Unable-To-Get-Data-Error/Description"/>
                </Description>
                <xsl:copy-of select="$_error/ns1:ErrorReport"/>
            </root>
        </pd:inputBindings>
    </pd:activity>
    <pd:transition>
        <pd:from>Start</pd:from>
        <pd:to>GetVariable</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>GetVariable</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>GetVariable</pd:from>
        <pd:to>CreateBusinessException</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-65536</pd:lineColor>
        <pd:conditionType>error</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>CreateBusinessException</pd:from>
        <pd:to>Generate Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>